BlogEngineApp/Models/Blog.cs
using System;
using System.Web;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.ComponentModel;
using BlogEngineApp.Models;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace BlogEngineApp
{
    public class Blog
    {
        public int BlogId { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }

        [DisplayFormat(ApplyFormatInEditMode = true,
               DataFormatString = "{0:dd/MMM}")]
        public DateTime DateCreated { get; set; }

        public ICollection<Post> Posts { get; set; }
    }
}

BlogEngineApp/Controllers/BlogController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BlogEngineApp;
using BlogEngineApp.Models;

namespace BlogEngineApp.Controllers
{ 
    public class BlogController : Controller
    {
        private BlogEngineAppContext db = new BlogEngineAppContext();
        private const int PostPerPage = 4;


        //
        // GET: /Blog/

        public ViewResult Index(int? id)
        {
            int pageNumber =  id ?? 0;
            IEnumerable<Blog> blogs = (from blog in db.Blogs
                                      orderby blog.BlogId descending
                                      select blog ).Skip(pageNumber * PostPerPage).Take(PostPerPage + 1);

            ViewBag.IsPreviousLinkVisible = pageNumber > 0;
            ViewBag.IsNextLinkVisible = blogs.Count() > PostPerPage;
            ViewBag.PageNumber = pageNumber;

            return View(blogs.Take(PostPerPage));
        }


        public ViewResult OpenBlog(int blogId)
        {
            Blog blog = db.Blogs.Include("Posts").Where(b => b.BlogId == blogId).FirstOrDefault();

            return View("OpenBlog", blog);
        }


        /*
        public ViewResult Index()
        {
            return View(db.Blogs.ToList());
        }

        */


        //
        // GET: /Blog/Details/5

        public ViewResult Details(int id)
        {
            Blog blog = db.Blogs.Find(id);
            return View(blog);
        }

        //
        // GET: /Blog/Create



        public ActionResult Create()
        {
            if (User.Identity.IsAuthenticated)
            {
                Blog blog = new Blog();
                blog.DateCreated = DateTime.Now;
                return View(blog);
            }
            else
                return RedirectToAction("Index");
        } 

        //
        // POST: /Blog/Create

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Create(Blog blog)
        {
            if (ModelState.IsValid)
            {
                db.Blogs.Add(blog);
                db.SaveChanges();
                return RedirectToAction("Index");  
            }

            return View(blog);
        }
        
        //
        // GET: /Blog/Edit/5
 
        public ActionResult Edit(int id)
        {
            if (User.Identity.IsAuthenticated)
            {
                Blog blog = db.Blogs.Include("Posts").Where(b => b.BlogId == id).FirstOrDefault();
                return View(blog);
            }

            return RedirectToAction("Index");
        }

        //
        // POST: /Blog/Edit/5

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Edit(Blog blog)
        {
            if (ModelState.IsValid)
            {
                db.Entry(blog).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(blog);
        }

        //
        // GET: /Blog/Delete/5
 
        public ActionResult Delete(int id)
        {
            Blog blog = db.Blogs.Find(id);
            return View(blog);
        }

        //
        // POST: /Blog/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateInput(false)]
        public ActionResult DeleteConfirmed(int id)
        {            
            Blog blog = db.Blogs.Find(id);
            db.Blogs.Remove(blog);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ViewResult Galery()
        {
            return View();
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

BlogEngineApp/Controllers/FriendController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BlogEngineApp.Models;

namespace BlogEngineApp.Controllers
{ 
    public class FriendController : Controller
    {
        private BlogEngineAppContext db = new BlogEngineAppContext();

        //
        // GET: /Friend/

        public ViewResult Index()
        {
            return View(db.Friends.ToList());
        }

        [HttpGet]
        public ViewResult Birthday()
        {
            if (User.Identity.IsAuthenticated)
            {
                IList<Friend> friends = db.Friends.Where(f => f.BirthDate.Day == DateTime.Now.Day && f.BirthDate.Month == DateTime.Now.Month).ToList();

                return View(friends);
            }
            else
                return View("Create");
        }


        //
        // GET: /Friend/Details/5

        public ViewResult Details(int id)
        {
            Friend friend = db.Friends.Find(id);
            return View(friend);
        }

        //
        // GET: /Friend/Create

        public ActionResult Create()
        {
            return View();
        } 

        //
        // POST: /Friend/Create

        [HttpPost]
        public ActionResult Create(Friend friend)
        {
            if (ModelState.IsValid)
            {


                db.Friends.Add(friend);
                db.SaveChanges();
                if (User.Identity.IsAuthenticated)
                {
                    return RedirectToAction("Index");
                }
                else
                    return RedirectToAction("Index", "Blog");
            }

            return View(friend);
        }


       
        
        //
        // GET: /Friend/Edit/5
 
        public ActionResult Edit(int id)
        {
            Friend friend = db.Friends.Find(id);
            return View(friend);
        }

        //
        // POST: /Friend/Edit/5

        [HttpPost]
        public ActionResult Edit(Friend friend)
        {
            if (ModelState.IsValid)
            {
                db.Entry(friend).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(friend);
        }

        //
        // GET: /Friend/Delete/5
 
        public ActionResult Delete(int id)
        {
            Friend friend = db.Friends.Find(id);
            return View(friend);
        }

        //
        // POST: /Friend/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {            
            Friend friend = db.Friends.Find(id);
            db.Friends.Remove(friend);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

BlogEngineApp/Controllers/PostController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BlogEngineApp.Models;

namespace BlogEngineApp.Controllers
{ 
    public class PostController : Controller
    {
        private BlogEngineAppContext db = new BlogEngineAppContext();

        //
        // GET: /Post/

        public ViewResult Index()
        {
            return View(db.Posts.ToList());
        }

        //
        // GET: /Post/Details/5

        public ViewResult Details(int id)
        {
            Post post = db.Posts.Find(id);
            return View(post);
        }

        //
        // GET: /Post/Create
        [HttpGet]
        public ActionResult Create(int blogId)
        {
            BlogPostViewModel model = new BlogPostViewModel();
            model.BlogId = blogId;
            model.Post = new Post();
            model.Post.DateCreated = DateTime.Now;
            return View(model);
        } 

        //
        // POST: /Post/Create

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Create(BlogPostViewModel model, HttpPostedFileBase image)
        {
            if (ModelState.IsValid)
            {
                Blog blog = db.Blogs.Include("Posts").Where(b => b.BlogId == model.BlogId).FirstOrDefault();
                if (image != null)
                {
                    model.Post.ImageMimeType = image.ContentType;
                    model.Post.ImageData = new byte[image.ContentLength];
                    image.InputStream.Read(model.Post.ImageData, 0, image.ContentLength);
                }

                blog.Posts.Add(model.Post);
                db.Entry(blog).State = EntityState.Modified;
                db.SaveChanges();
            }

            return RedirectToAction("OpenBlog", "Blog", new { blogId = model.BlogId});
        }


        public FileContentResult GetImage(int postId)
        {
            Post post = db.Posts.FirstOrDefault(p => p.PostId == postId);
            if (post != null)
            {
                return File(post.ImageData, post.ImageMimeType);
            }
            else
            {
                return null;
            }
        }

        public ActionResult GetPostsForBlog(int blogId)
        {
            IList<Post> posts = db.Posts.Include("Blog").Where(p => p.Blog.BlogId == blogId).ToList();

            return View(posts);
        }
        
        //
        // GET: /Post/Edit/5
 
        public ActionResult Edit(int id)
        {
            Post post = db.Posts.Find(id);
            return View(post);
        }

        //
        // POST: /Post/Edit/5

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Edit(Post post)
        {
            if (ModelState.IsValid)
            {
                db.Entry(post).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(post);
        }

        //
        // GET: /Post/Delete/5
 
        public ActionResult Delete(int id)
        {
            Post post = db.Posts.Find(id);
            return View(post);
        }

        //
        // POST: /Post/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {

            Post post = db.Posts.Find(id);
            db.Posts.Remove(post);
            db.SaveChanges();
            return RedirectToAction("OpenBlog", "Blog", new { blogId = post.BlogId });
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

BlogEngineApp/Views/Blog/Create.cshtml
@model BlogEngineApp.Blog

@{
    ViewBag.Title = "Create new post";
    Layout = "~/Views/Shared/_Layout.cshtml";
}



<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/ckeditor/ckeditor.js")"    type="text/javascript"></script>
<script src="@Url.Content("/ckeditor/adapters/jquery.js")" type="text/javascript"></script>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)
    

        <div class="editor-label">
            Наслов на пост
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Title)
            @Html.ValidationMessageFor(model => model.Title)
        </div>

        <div class="editor-label">
            @Html.TextBox("DateCreated", Model.DateCreated.ToString("dd/MM/yyyy"), new { style = "width: 120px" })
        </div>


        <div class="editor-label">
           Содржина
        </div>
        <div class="textarea">
        @Html.TextAreaFor(model => model.Description, new { @class="adminRichText"})
        @*    @Html.TextAreaFor(model => model.Description, new { cols = "60%" ,rows = "20"}) *@
            @Html.ValidationMessageFor(model => model.Description)
        </div>

        
        

        <p>
            <input type="submit" value="Додади" />
        </p>
   
}

<div>
    @Html.ActionLink("Назад кој листата", "Index")
</div>

<script language="javascript" type="text/javascript">
jQuery(".adminRichText").ckeditor();
</script>

BlogEngineApp/Views/Blog/Delete.cshtml
@model BlogEngineApp.Blog

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Дали сакате да го избришете овој пост?</h2>



<div class="BlogContainer">
          
        
        <div class = "BlogCreated">
          
           @Html.DisplayFor(model => model.DateCreated)
        </div>

        <div class="BlogContent">
            
          @*  @Html.DisplayFor(model => model.Description) *@
          @Html.Raw(Model.Description)
            </div>

       
        
   
   </div>

@using (Html.BeginForm()) {
    
        <input type="submit" value="Избриши" /> 
        <br/>
        @Html.ActionLink("Назад кон почетна", "Index")
   
}

BlogEngineApp/Views/Blog/Details.cshtml
@model BlogEngineApp.Blog

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<fieldset>
    <legend>Blog</legend>

    <div class="display-label">Title</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Title)
    </div>

    <div class="display-label">Description</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Description)
    </div>

    <div class="display-label">DateCreated</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.DateCreated)
    </div>
</fieldset>
<p>
    @Html.ActionLink("Edit", "Edit", new { id=Model.BlogId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

BlogEngineApp/Views/Blog/Edit.cshtml
@model BlogEngineApp.Blog

@{
    ViewBag.Title = "Промена на пост";
    Layout = "~/Views/Shared/_Layout.cshtml";
}



<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/ckeditor/ckeditor.js")"    type="text/javascript"></script>
<script src="@Url.Content("/ckeditor/adapters/jquery.js")" type="text/javascript"></script>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)
   

        @Html.HiddenFor(model => model.BlogId)

        <div class="editor-label">
            Наслов
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Title)
            @Html.ValidationMessageFor(model => model.Title)
        </div>

        <div class="editor-label">
            Содржина
        </div>
        <div class="editor-field">

          @Html.TextAreaFor(model => model.Description, new { @class="adminRichText"})
        @*    @Html.TextAreaFor(model => model.Description, new { cols = "60%", rows = "20" }) *@
            @Html.ValidationMessageFor(model => model.Description)
        </div>

        
        <div class="editor-field">
            @Html.HiddenFor(model => model.DateCreated)
            @Html.ValidationMessageFor(model => model.DateCreated)
        </div>
        <br />
        

        <p>
            <input type="submit" value="Зачувај" />
        </p>
    
}

<div>
    @Html.ActionLink("Назад кон листата", "Index")
</div>


<script language="javascript" type="text/javascript">
    jQuery(".adminRichText").ckeditor();
</script>

BlogEngineApp/Views/Blog/Galery.cshtml
@{
    ViewBag.Title = "Galery";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<script src="@Url.Content("~/Scripts/jquery.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.lightbox-0.5.js")" type="text/javascript"></script>





<script type="text/javascript">
    $(function () {
        $('#gallery a').lightBox();
    });
</script>


<div class="pictures">
        <div id="gallery">
               <h2>Франција</h2>
         <ul>
                <li>
                    

                     <a href="@Url.Content("~/Content/Galery/image2.JPG")" title="Градините на версај">
                       <img src="@Href("~/Content/Galery/thumb_image2.JPG")" width="72" height="72" alt="" />
                     </a>

                     <a href="@Url.Content("~/Content/Galery/image3.JPG")" title="Дизниленд">
                       <img src="@Href("~/Content/Galery/thumb_image3.JPG")" width="72" height="72" alt="" />
                     </a>

                     <a href="@Url.Content("~/Content/Galery/image4.JPG")" title="Пристаниште во Франција">
                       <img src="@Href("~/Content/Galery/thumb_image4.JPG")" width="72" height="72" alt="" />
                     </a>

                     <a href="@Url.Content("~/Content/Galery/image5.JPG")" title="Ајфелова кула">
                       <img src="@Href("~/Content/Galery/thumb_image5.JPG")" width="72" height="72" alt="" />
                     </a>

                     <a href="@Url.Content("~/Content/Galery/image6.JPG")" title="Лувр">
                       <img src="@Href("~/Content/Galery/thumb_image6.JPG")" width="72" height="72" alt="" />
                     </a>

                     <a href="@Url.Content("~/Content/Galery/image7.JPG")" title="Поглед од ајфелова кула">
                       <img src="@Href("~/Content/Galery/thumb_image7.JPG")" width="72" height="72" alt="" />
                     </a>

                </li>
         </ul>


         <h2>Италија</h2>
         <ul>
                <li>
                    

                     <a href="@Url.Content("~/Content/Galery/image9.jpg")" title="Фиренца">
                       <img src="@Href("~/Content/Galery/thumb_image9.JPG")" width="72" height="72" alt="" />
                     </a>

                     <a href="@Url.Content("~/Content/Galery/image10.JPG")" title="Кривата кула во Пиза">
                       <img src="@Href("~/Content/Galery/thumb_image10.JPG")" width="72" height="72" alt="" />
                     </a>

                     <a href="@Url.Content("~/Content/Galery/image11.JPG")" title="Тиволи">
                       <img src="@Href("~/Content/Galery/thumb_image11.JPG")" width="72" height="72" alt="" />
                     </a>

                     <a href="@Url.Content("~/Content/Galery/image12.JPG")" title="Гробот на Јулија">
                       <img src="@Href("~/Content/Galery/thumb_image12.JPG")" width="72" height="72" alt="" />
                     </a>

                     <a href="@Url.Content("~/Content/Galery/image13.JPG")" title="Венеција">
                       <img src="@Href("~/Content/Galery/thumb_image13.JPG")" width="72" height="72" alt="" />
                     </a>

                     <a href="@Url.Content("~/Content/Galery/image14.JPG")" title="Црквата Св.Петар во Ватикан">
                       <img src="@Href("~/Content/Galery/thumb_image14.JPG")" width="72" height="72" alt="" />
                     </a>

                </li>
         </ul>


        </div>
 </div>

 <div>
    @Html.ActionLink("Врати се на почетна", "Index", "Blog")
</div>

BlogEngineApp/Views/Blog/Index.cshtml
@model IEnumerable<BlogEngineApp.Blog>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";

    bool isPriviousLinkVisible = ViewBag.IsPreviousLinkVisible ?? false;
    bool isNextLinkVisible = ViewBag.IsNextLinkVisible ?? false;
    
    
}

<div id="sidebar">
              <img id="portrait" src="@Href("~/Content/Images/myphoto.jpg")" alt="Portrait"  height="250" width = "200"/> </br> </br>

              

              <img id="friendrequest" src="@Href("~/Content/Images/friendrequest.jpg")" alt="friend"  height="150" width = "100"/> </br>

              @Html.ActionLink("Станете мој пријател", "Create", "Friend")

              <br/>

              @if (User.Identity.IsAuthenticated)
              {
              @Html.ActionLink("Денес имаат роденден", "Birthday", "Friend")
              }
</div>


<div id= "leftside">
 
 <h2> Галерија </h2>
 
 <a href="@Url.Action("Galery","Blog")"><img id="photo" src="@Url.Content("~/Content/Galery/francija.gif")" alt="Blog" height="150" width = "120" /></a>
 <br/>
  Франција
 </div>

 
 
@if (User.Identity.IsAuthenticated)
{
    <h1>
    @Html.ActionLink("Додади нов пост", "Create")
    </h1>

}





 


@foreach (var item in Model) {
   
          <div class="BlogTitle">
          @Html.ActionLink(item.Title, "OpenBlog", "Blog", new { blogId=item.BlogId },null)
          </div>
        
    <div class="BlogContainer">
          
        
        <div class = "BlogCreated">
          @*  @Html.DisplayFor(modelItem => item.DateCreated.Month)*@
           @Html.DisplayFor(modelItem => item.DateCreated)
        </div>

        <div class="BlogContent">
            @if (item.Description.Length > 555)
            {
                item.Description = string.Format("{0} ...", item.Description.Substring(0, 554));
            }
          
          @*  @Html.DisplayFor(modelItem => item.Description) *@
                @Html.Raw(item.Description)
            </div>

        <div class="PostsNumber">

       
            @Html.DisplayFor(modelItem => item.Posts)
        

         
        </div>
        @if (User.Identity.IsAuthenticated)
        {
        <div class="BlogLinks">
        
           
            @Html.ActionLink("Промени", "Edit", new { id = item.BlogId }) |
            
            @Html.ActionLink("Избриши", "Delete", new { id = item.BlogId }) 
       </div>
        }
   </div>
}

@if (isPriviousLinkVisible)
{
    <a id="previousLink" href="@Href("~/Blog/Index/" + (ViewBag.PageNumber - 1))"> &lt Претходна страна </a>
}

@if (isNextLinkVisible)
{
    <a id="nextLink" href="@Href("~/Blog/Index/" + (ViewBag.PageNumber + 1))">  Следна страна &gt </a>
}

BlogEngineApp/Views/Blog/OpenBlog.cshtml
@model BlogEngineApp.Blog



@{
    ViewBag.Title = "OpenBlog";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="BlogTitle">
          @Html.DisplayFor(model => model.Title)
          </div>

<div class="BlogContainer">
          
        
        <div class = "BlogCreated">
          
           @Html.DisplayFor(model => model.DateCreated)
        </div>

        <div class="BlogContent">
            
          @*  @Html.DisplayFor(model => model.Description) *@
          @Html.Raw(Model.Description)
            </div>

       
   
   </div>

   @foreach (BlogEngineApp.Models.Post post in Model.Posts)
   {
    

         
     <div class="CommentContainer">
        <div class="CommentTitle">
               <div class="CommentImage">
        @if (post.ImageData != null) { 
               <div style="float:left;margin-right:20px"> 
                    <img width="45" height="45" src="@Url.Action("GetImage", "Post", 
                         new { post.PostId })" alt="" /> 
               </div> 
           } 
           </div>
          
            @Html.DisplayFor(modelItem => post.Title)
            ::
        </div>
        <div class="CommentContent">
            @Html.DisplayFor(modelItem => post.Content)
        </div>
        <div class="CommentDate">
            @Html.DisplayFor(modelItem => post.DateCreated)
        </div>

        

        @if (User.Identity.IsAuthenticated)
        {
        <div>
            
            @Html.ActionLink("Избриши", "Delete", "Post", new { id = post.PostId }, null)
        </div>
        }
   </div>
}

<div = class="NewPost">
<button onclick="location.href='@Url.Action("Create", "Post", new { blogId = Model.BlogId })'">Остави коментар</button>
</div>

<div>
    @Html.ActionLink("Врати се на насловна", "Index", "Blog")
</div>